name: Publish CLI

on:
  push:
    branches: [main]

jobs:
  publish-cli:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]

    runs-on: ${{ matrix.os }}-latest

    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: 1.6.3
      - run: make compile-${{ matrix.os }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: publish cli
          push_options: --force
